name: Weekly Cache Update

on:
  schedule:
    - cron: '0 7 * * 4' # 2 AM Central Time (CDT is UTC-5, so 2+5=7)
  workflow_dispatch:

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: List scripts directory for debugging
        run: ls -l scripts

      - name: Make script executable
        run: chmod +x scripts/doTheThing.sh

      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Run cache update script (ignore lint errors)
        run: ./scripts/doTheThing.sh || true
        env:
          SHEETDB_URL: ${{ secrets.SHEETDB_URL }}
          SHEETDB_API_ID: ${{ secrets.SHEETDB_API_ID }}
          SHEETDB_API_KEY: ${{ secrets.SHEETDB_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false

      - name: Stage updated cache
        run: git add public/

      - name: Commit cache update
        run: |
          git commit -m "Update cache" || echo "No changes to commit"

      - name: Push cache update
        run: git push origin HEAD

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
